sudo: required
language: node_js
node_js:
  - "8"

notifications:
  email:
    on_success: never

install:
  - npm install -g yarn
  - npm install -g codecov
  - npm install -g lerna
  - lerna bootstrap

script:
  - yarn test:coverage
