sudo: required
language: node_js
node_js:
  - "6"

notifications:
  email:
    on_success: never

install:
  - npm install -g codecov
  - npm install -g lerna
  - lerna bootstrap

script: npm run test:coverage