sudo: required
language: node_js
node_js:
  - "8"

notifications:
  email:
    on_success: never

install:
  - npm install -g yarn
  - npm install -g codecov
  - npm install -g lerna
  - npm install -g https://github.com/google/js-green-licenses.git\#494a457
  - lerna bootstrap

script:
  - jsgl --local .
  - yarn build
  - yarn test:coverage
